name: Flutter Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.0
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: |
          flutter test --coverage \
            --dart-define BANNER_AD_UNIT_ID=ca-app-pub-3940256099942544/6300978111 \
            --dart-define INTERSTITIAL_AD_UNIT_ID=ca-app-pub-3940256099942544/1033173712
      - name: Build release APK
        run: |
          flutter build apk --release \
            --dart-define BANNER_AD_UNIT_ID=${{ secrets.BANNER_AD_UNIT_ID }} \
            --dart-define INTERSTITIAL_AD_UNIT_ID=${{ secrets.INTERSTITIAL_AD_UNIT_ID }}
      - name: Upload Crashlytics symbols
        run: ./gradlew app:uploadCrashlyticsSymbolFileRelease
        working-directory: android
